baseURL = 'https://608z.com/'
languageCode = 'en-us'
title = '608z.com'
theme = 'hugo-theme-console'

[params]
  # Shorten the title to two characters on mobile
  titleCutting = true
  animateStyle = 'animated zoomIn fast'

  [[params.navlinks]]
    name = 'home/'
    url = '/'

  [[params.navlinks]]
    name = 'role-with-it/'
    url = 'role-with-it/'
